# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 3.0'

- script: |
    ls
    gem install bundler
    bundle install
  displayName: 'bundle install'
- script: |
    
    cat Gemfile
    bundle install
  displayName: 'gemfile install'  
- script: |
    ls
    gem install capybara
  
  displayName: 'capybara install'

- script: |
    echo %cd%
    ls
  displayName: 'cd'
- script: cucumber
  displayName: 'cucumber'
