# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 3.0'

- script: |
    gem install bundler
    bundle install
  displayName: 'bundle install'
- script: |
    bundle install
  displayName: 'gemfile install'  

- script: |
    cat cucumber.yml
    cucumber
  displayName: 'cucumber'

- task: PublishCucumberReport@1
  inputs:
    jsonDir: 'out/'
    outputPath: 'out/'
    theme: 'bootstrap'
    reportSuiteAsScenarios: true
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'    
