# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.7.2'

- script: |
    gem install bundler
  displayName: 'bundle install'
- script: |
    bundle install
  displayName: 'gemfile install'  

- script: |
    cucumber --format html --out out/index.html -f pretty
  displayName: 'cucumber --format json --out out/cucumber.json'
