# Ruby
# Package your Ruby project.
# Add steps that install rails, analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/ruby

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 3.0'

- script: |
    gem install bundler
    bundle install
  displayName: 'bundle install'
- script: |
    gem install cucumber -v 2.4.0
  displayName: 'bundle install'

- script: |
    echo %cd%
  displayName: 'cd'
- script: cucumber
  displayName: 'cucumber'
